### ISSUE TITLE
Not work build only with plugin pages

### ISSUE THREAD

**Issue by alkorlos** [vituum/vite-plugin-nunjucks#3]
Hello!

Based on an example [vituum + nunjucks](https://stackblitz.com/github/vituum/vituum/tree/main/examples/nunjucks)

If change config to:

```js
import pages from 'vituum/plugins/pages.js';

import nunjucks from '@vituum/vite-plugin-nunjucks'

export default {
    build: {
        rollupOptions: {
            input: ['./src/pages/hello.njk'],
        },
    },
    plugins: [
        pages(),
        nunjucks({
            root: './src'
        })
    ],
}
```

That is, use only the plugin pages without plugin imports:
`npm run dev` work
`npm run build` give error
```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /home/projects/wmaijvarr.github/src/pages/hello.njk:1:1
1: {% include 'layouts/main.njk' %}
    ^
error during build:
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:2270:30)
    at Module.error (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:13699:16)
    at Module.tryParse (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:14430:25)
    at Module.setSource (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:14031:39)
    at ModuleLoader.addModuleSource (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:24550:20)
```

In this case rollupOptions.input:
```js
rollupOptions: {
    input: ['./src/pages/hello.njk'],
},
```
Need because without rollupOptions.input if use only plugin pages error:
```
Could not resolve entry module "index.html".
error during build:
RollupError: Could not resolve entry module "index.html".
    at error (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:2270:30)
    at ModuleLoader.loadEntryModule (/home/projects/wmaijvarr.github/node_modules/rollup/dist/es/shared/node-entry.js:24782:20)
```

**Comment by lubomirblazekcz** [comment]
If you are not using vituum core and only pages as separate plugin you need to add files manually to `rollupOptions.input` with `.html` extention, if you want to use globs you need to use fast-glob.

I will make this easier to use vituum core without imports, since that is something many want to disable as I can see.

**Comment by alkorlos** [comment]
Yes, if i config above rename `hello.njk` to `hello.html` and rename this file all work. Thank you!

**Comment by lubomirblazekcz** [comment]
.njk.html actually 👍
